Repository EcoGrow/ecogrow-frontend, pull requests merged in 2024-11, with the labels that each got.

#13 [2024/11/01] Feat/recycling game
  src/App.js
  src/api/auth.js
  src/components/Logout.js
  src/page/MainPage.js
  src/page/RecyclingTips.css
  src/page/RecyclingTips.js
  src/page/WasteRecord.js
  src/page/WasteRecordDetail.js
  src/page/WasteRecordWrite.js
Labels: feat

#16 Fix/recyclingtips
  src/page/MainPage.js
  src/page/NewsPage.js
  src/page/RecyclingTips.css
  src/page/RecyclingTips.js
  src/page/WasteRecord.js
  src/page/WasteRecordDetail.js
  src/page/WasteRecordWrite.js
Labels: fix

#18 [2024/11/05] Fix/my page 마이 페이지 UI, 디자인 수정
  src/App.js
  src/page/MyPage.css
  src/page/MyPage.js
  src/page/WasteRecordDetail.css
  src/page/WasteRecordWrite.css
Labels: fix

#20 Feat/image animation
  src/components/ChatModal.css
  src/components/ChatModal.js
  src/components/Logout.js
  src/page/Auth/LoginForm.js
  src/page/FloatingButton.css
  src/page/FloatingButton.js
  src/page/MainPage.js
  src/page/MyPage.js
  src/page/NewsPage.css
  src/page/NewsPage.js
  src/page/RecyclingTips.css
  src/page/RecyclingTips.js
  src/page/WasteRecord.css
  src/page/WasteRecord.js
  src/page/WasteRecordDetail.js
  src/page/WasteRecordWrite.js
Labels: feat

#26 프론트 다양한 기능 및 버튼 등 여러가지 생성과 수정
  free-icon-person-2815428.png
  src/components/ChatModal.css
  src/components/ChatModal.js
  src/components/Logout.js
  src/pages/MainPage.css
  src/pages/MainPage.js
  src/pages/MyPage.css
  src/pages/MyPage.js
  src/pages/NewsPage.js
  src/pages/Product.css
  src/pages/Product.js
  src/pages/RecyclingTips.css
  src/pages/RecyclingTips.js
  src/pages/WasteRecord.css
  src/pages/WasteRecord.js
  src/pages/WasteRecordDetail.js
  src/pages/WasteRecordWrite.js
Labels: feat, fix
